#!/system/bin/sh
# ni sh buat ganti mode paling cepet di dunia AWKWKWKWK
echo 'preparing . . .'
magisk=$(ls /data/adb/magisk/magisk || ls /sbin/magisk) 2>/dev/null;
GetVersion=$($magisk -c | grep -Eo '[0-9]{2}\.[0-9]+')
case "$GetVersion" in
'15.'[1-9]*) # Version 15.1 - 15.9
	ModulPath=/sbin/.core/img
;;
'16.'[1-9]*) # Version 16.1 - 16.9
	ModulPath=/sbin/.core/img
;;
'17.'[1-3]*) # Version 17.1 - 17.3
	ModulPath=/sbin/.core/img
;;
'17.'[4-9]*) # Version 17.4 - 17.9
	ModulPath=/sbin/.magisk/img
;;
'18.'[0-9]*) # Version 18.x
	ModulPath=/sbin/.magisk/img
;;
'19.'[0-9a-zA-Z]*) # Version 19.x
	ModulPath=/data/adb/modules
;;
'20.'[0-9a-zA-Z]*) # Version 20.x
	ModulPath=/data/adb/modules
;;
*)
    echo "unsupported magisk version detected,fail"
    exit 
;;
esac
ModulId="Thermal_ZyC_mpm2"
StatusThermal="$(cat "$ModulPath/$ModulId/system/vendor/etc/thermal-status.txt")"
if [ ! -z "$1" ];then
	if [ "$1" == "0" ];then
		echo "set to stock thermal"
		nohup sh $ModulPath/$ModulId/service.sh "0"  >/dev/null 2>&1 & 
	elif [ "$1" == "1" ];then
		echo "set to v3.2 thermal"
		nohup sh $ModulPath/$ModulId/service.sh "1"  >/dev/null 2>&1 & 
	elif [ "$1" == "2" ];then
		echo "set to latest thermal"
		nohup sh $ModulPath/$ModulId/service.sh "2"  >/dev/null 2>&1 & 
	fi
	echo "done . . ."
else
	StatusThermalDescription="unknow"
	if [ "$StatusThermal" == "0" ];then
		StatusThermalDescription="stock"
	elif  [ "$StatusThermal" == "1" ];then
		StatusThermalDescription="from v3.2"
	elif  [ "$StatusThermal" == "2" ];then
		StatusThermalDescription="from v4.8"
	fi
	echo "--- --- --- --- --- --- --- --- --- ---"
	echo "current status module : $StatusThermalDescription"
	echo "";
	echo "how to change :";
	echo "just type code bellow after zyc_thermal";
	echo "0 > from stock thermal.conf"
	echo "1 > from v3.2 thermal.conf"
	echo "2 > latest thermal.conf"
	echo "--- --- --- --- --- --- --- --- --- ---"
	echo "example: zyc_thermal 0"
fi